[package]
name = "esrc-ext"
version = "0.4.0"
edition = "2024"
authors = ["Eduardo Loback <...>", "Mateus Barbosa <barbosamat16@gmail.com>"]
description = "Extensions for ESRC, an event-sourcing library for Rust."
readme = "README.md"
repository = "https://github.com/eloback/esrc-ext"
license = "MIT"
keywords = ["esrc", "extensions", "event-sourcing"]
categories = ["asynchronous", "data-structures", "encoding", "serialization"]

[dependencies]
esrc = { git = "https://github.com/eloback/esrc.git", version = "0.3.0", features = [
    "derive",
] }
nats-dead-letter = { git = "https://github.com/eloback/nats-dead-letter.git", version = "0.2.0" }
opentelemetry-nats = { path = "./crates/opentelemetry-nats" }
axum = "0.8"
serde = { version = "1.0", features = ["derive"] }
uuid = { version = "1.0", features = ["v7", "serde"] }
thiserror = "2.0"
serde_json = "1.0"
async-nats = "0.46"
tracing = "0.1"
sqlx = { version = "0.8", features = [
    "runtime-tokio-rustls",
    "postgres",
    "uuid",
    "chrono",
] }
discern = "0.1.0"
tokio-util = { version = "0.7", features = ["rt"] }
tokio = { version = "1.0", features = ["rt"] }
stream-cancel = "0.8"
trait-variant = "0.1"
futures = "0.3.31"

[dev-dependencies]
tokio = { version = "1.0", features = ["full"] }
tracing-subscriber = "0.3"

[features]
default = []
