condense_wildcard_suffixes = true
doc_comment_code_block_width = 100
format_code_in_doc_comments = true
format_macro_bodies = true
format_macro_matchers = true
group_imports = "StdExternalCrate"
hex_literal_case = "Upper"
imports_granularity = "Module"
imports_layout = "HorizontalVertical"
match_block_trailing_comma = true
normalize_comments = true
single_line_if_else_max_width = 0
single_line_let_else_max_width = 0
style_edition = "2021"
use_try_shorthand = true
wrap_comments = true
